# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf1d8b0e6ca05b8458dc4f5ba18d4317704a097c724799e53253712a6625bd075132a12b844ce611d1d8e6f19c17bea7841f69f8d59585964f6310580e47faed

test:
  secret_key_base: 2e7c83bfb1b0331e8ebf6f199c08c5a160cc20dc32ecf158495f36226552f307d7fe26203c5522aac6c8f35ab167e333c6d654700846da3dd4d066a4ebb38bbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
