Movie.create(name: 'Movie1')
Movie.create(name: 'Movie2')
Actor.create(name: 'Actor1', age: 20, weight: 60, height:170)
Actor.create(name: 'Actor2', age: 30, weight: 80, height:185)
Actor.create(name: 'Actor3', age: 25, weight: 50, height:160)
Actor.create(name: 'Actor4', age: 47, weight: 65, height:172)
Actor.create(name: 'Actor5', age: 60, weight: 57, height:162)
AttributeType.create(name: 'Actor1')
AttributeType.create(name: 'Actor2')
AttributeType.create(name: 'Actor3')
AttributeType.create(name: 'Actor4')
AttributeType.create(name: 'Actor5')
AttributeType.create(name: 'Actor1')
AttributeType.create(name: 'Actor2')
AttributeType.create(name: 'Actor3')
AttributeType.create(name: 'Actor4')
AttributeType.create(name: 'Actor5')
MovieActor.create(movie_id: 1, actor_id: 1)
MovieActor.create(movie_id: 1, actor_id: 2)
MovieActor.create(movie_id: 1, actor_id: 4)
MovieActor.create(movie_id: 2, actor_id: 2)
MovieActor.create(movie_id: 2, actor_id: 3)
MovieActor.create(movie_id: 2, actor_id: 5)
Setting.create(setting_value: 'Val1', attribute_type_id: 1, actor_id: 1)
Setting.create(setting_value: 'Val2', attribute_type_id: 1, actor_id: 1)
Setting.create(setting_value: 'Val2', attribute_type_id: 2, actor_id: 4)
Setting.create(setting_value: 'Val4', attribute_type_id: 2, actor_id: 2)
Setting.create(setting_value: 'Val3', attribute_type_id: 3, actor_id: 2)
Setting.create(setting_value: 'Val4', attribute_type_id: 2, actor_id: 2)
Setting.create(setting_value: 'Val4', attribute_type_id: 4, actor_id: 3)
Setting.create(setting_value: 'Val4', attribute_type_id: 4, actor_id: 3)
Setting.create(setting_value: 'Val2', attribute_type_id: 5, actor_id: 5)
Setting.create(setting_value: 'Val4', attribute_type_id: 5, actor_id: 5)
